### ISSUE TITLE
frida-ls-devices cannot detect multiple devices more than 4

### ISSUE THREAD

**Issue by hanjideng** [frida/frida-tools#9]
I use Ubuntu Desktop 16.04,  frida-tools == 1.2.2, frida == 12.2.9
When I plugin 2 Nexus 5P, 1 Nexus5, 3 Nexus 6, total 6 devices, the frida-ls-devices only show 4 devices: 1 nexus 5P, 3 Nexus 6
Does frida support limited number of devices?

**Comment by oleavr** [comment]
No, this is because Frida's Droidy backend – which communicates with adb – [considers itself started](https://github.com/frida/frida-core/blob/31f42414689fd81878fd0d2466d88933bbceed2e/src/droidy/droidy-host-session.vala#L11) if it takes >= 500 ms to enumerate its devices. The trade-off is that we don't want to have an unbounded delay at startup preventing Frida's APIs from being used, vs. having the initial `enumerate_devices()` be as complete as possible. If you were to use the Frida API yourself though and listen for the `added` / `removed` / `changed` signals on `DeviceManager`, you will see all devices appear... perhaps we can make `frida-ls-devices` wait a bit before it exits. PRs welcome!
